---
title: "tissue_example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tissue_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(CompassR)
library(httr)
library(jsonlite)
library(ggplot2)
library(cowplot)
library(ggforce)
library(dplyr)
library(Seurat)
library(Gviz)
library(GenomicRanges)
library(biomaRt)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggdendro)
library(cowplot)
library(ggtree) # install with `devtools::install_github("YuLab-SMU/ggtree")` as you need a version newer than what bioconductor serves
library(patchwork)
library(aplot)
library(ggplotify)
library(RColorBrewer)

### quick run example
CompassR:::quick_example_compassr("Myh6")
```

```{r}
## Example for Myh6 in mouse heart sample
expr_vec = query_exprssion("mm10", "Myh6")
link_res = query_linkage("mm10", "Myh6")

link_df = link_res[["linkage"]]
sample_df = link_res[["samples"]]

sample_df = sample_df[sample_df$donor_gender == "Male", ]
sample_df = sample_df[, c("sample_id", "bio_source")]
colnames(sample_df) = c("Sample", "Group")
sample_df = sample_df[order(sample_df$Group), ]

link_df = link_df[link_df$sample %in% sample_df$Sample, ]

expr_df = data.frame(t(expr_vec)[sample_df$Sample, ])
colnames(expr_df) = c("Gene")
expr_df$Sample = rownames(expr_df)
```

```{r}
link_df$sample_id = link_df$sample
genome_track_map(link_df, sample_df, "Myh6", expr_df, assembly = "mm10", legend.position="left", t = -20, b = 20)
```
```{r}
track_plot = plot_genome_track(link_df, "Myh6", "mm10", sample_df$Sample)
peaks = track_plot[[length(track_plot)]]
peaks$name = as.character(peaks$name)
peak_order = make_peak_group(link_df, peaks, sample_df)

ht_peak_order = peak_order[peak_order[, 2] >= 0.5 & peak_order[, 1]<0.5 & peak_order[, 3]<0.5 & peak_order[, 4]<0.5, ]
ht_peaks = rownames(ht_peak_order)

peak_vec = sub(":", "-", as.character(peaks))
ht_peaks = peak_vec[as.numeric(ht_peaks)]


tf = tf_binding("mm10", paste0(ht_peaks, collapse = "_"))
p = plot_giggle(tf)
p
```


